sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
bundler_args: "--jobs=3 --retry=3"

before_install:
  - bundle config build.nokogiri --use-system-libraries

script:
  - bundle exec rake spec
